sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    fast_failure: true
    include:
        - php: 5.3.3
          env: dependencies=lowest

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable --prefer-source --no-interaction; else composer install --prefer-source --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
